os: osx
# We only need OSX to make the libvips install easier:
# Debian packages are available, but not for versions that Travis supports? Argh.
addons:
  homebrew:
    packages:
      - vips
language: python
python:
  - '3.6'
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - ./test.sh
