# The following is sourced from https://github.com/libvips/pyvips/blob/master/.travis.yml

env:
  global:
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=7
    - VIPS_VERSION_MICRO=1
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

dist: trusty

addons:
  apt:
    packages:
      - libexpat1
      - gettext
      - liblcms2
      - libmagickwand
      - libopenexr
      - libcfitsio3
      - libgif
      - libgs
      - libgsf-1-dev
      - libmatio
      - libopenslide
      - liborc-0.4
      - libpango1.0
      - libpoppler-glib
      - librsvg2
      - libwebp
      - libfftw3
      - libglib2.0

# The following is our own code

language: python
python:
  - '3.6'
cache: pip

# The following is sourced from https://github.com/libvips/pyvips/blob/master/.travis.yml

before_install:
  - ./install-vips.sh --without-python
  - pip install -U setuptools

# The following is our own code

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - ./test.sh
