language: python
python:
  - '3.6'
cache: pip
before_install:
  - sudo apt-get install python3-gi gir1.2-vips-8.0
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - vips list classes
  - ./test.sh
