name: vitessce-data-uf-cells-spleen-0510
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8.2
  - numpy==1.18.4
  - scipy==1.4.1
  - pandas==1.0.3
  - networkx==2.4
  - snakemake==5.17.0
  - nb_conda==2.2.1
  - anndata==0.7.1
  - pyarrow==0.15.1
  - h5py==2.10.0
  - pyyaml==5.3.1
  - pip
  - pip:
    - obonet==0.2.5